config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :profiles
  resources :order
  resources :cart_items
  resources :products
  resources :cart_items
  resources :carts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items

  def cart_items
    cart_items = []
    session[:cart].each do |item|
      cart_items << Product.find(item)
    end
    cart_items
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  
  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_one :order, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  def current_cart
    session[:cart] ||= []
  end
end

app/controllers/cart_item_controller.rb
class CartItemController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def index
    @cart = session[:cart]
  end

  def create
    @cart_item = CartItem.new(cart_params)
    @cart_item.product = Product.find(params[:product_id])
    session[:cart] << @cart_item
  end

  private

  def cart_params
    params.require(:product).permit(:name, :product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_cart
  end

  def add_to_cart
    current_cart.each do |item|
      @cart.push(item.name)
      @cart
    end
  end

  def show
    @cart = current_cart
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    current_cart << {name: @product.name, price: @product.price}

    session[:cart] = current_cart
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:name, :address, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/cart_items/index.html.erb
<h1>Items in your Cart</h1>

<% @cart.each do |item| %>
<%= item.name %>
<% end %>

app/views/carts/index.html.erb
<% current_cart.each do |hash| %>
<% hash.each do |key,value| %>
<p style="color:yellow;"><%= value %></p>
<% end %>
<% end %>

<%= link_to do %>
<div class="btn btn-primary">
  CHECKOUT
</div>

<% end %>

app/views/products/index.html.erb
<div class="container">
  <div class="text-left">
    <%= form_tag products_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Products...", class:"search_bar" %>
      <%= submit_tag "Search",  class: "search_bar_submit" %>
    <% end %>
  </div>
</div>

<h1>Welcome to The Whiskey Wall</h1>
<% @products.each do |product| %>
<div class="col-md-4">

    <%= link_to product do %>
      <div>
        <%= image_tag product.image_url, class:"whiskey_images" %>
        <h2><%= product.name %></h2>
      </div>
      <% end %>
  </div>
<% end %>

app/views/products/show.html.erb
<%= image_tag @product.image_url, class: "product-image float-left" %>
<div class="product-info float-left">
<h1><%= @product.name %></h1>
<p>$<%= @product.price %></p>
<p><%= @product.description %></p>
<p>age: <%= @product.age %></p>
<%= link_to "Add to cart", cart_path(@product.id), method: :put, class: "add-cart" %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit (@profile.new_record? ? "Save" : "Update"), class: "btn btn-default" %>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
<%end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>