config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :profiles
  resources :order
  resources :cart_items
  resources :products
  resources :cart_items
  resources :carts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items

  def cart_items
    cart_items = []
    session[:cart].each do |item|
      cart_items << Product.find(item)
    end
    cart_items
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  
  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_one :order, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cart_item_controller.rb
class CartItemController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def index
    @cart = session[:cart]
  end

  def create
    @cart_item = CartItem.new(cart_params)
    @cart_item.product = Product.find(params[:product_id])
    session[:cart] << @cart_item
  end

  private

  def cart_params
    params.require(:product).permit(:name, :product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_cart
  end

  def add_to_cart
    current_cart.each do |item|
      @cart.push(item.name)
      @cart
    end
  end

  def show
    @cart = current_cart
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    current_cart << {name: @product.name, price: @product.price}

    session[:cart] = current_cart
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:name, :address, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiskeyStore</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Cinzel|Great+Vibes|Josefin+Slab|Julius+Sans+One" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to carts_path do %>
    <h3 class="cart">Shopping Cart<i class="fa fa-shopping-cart" aria-hidden="true"></i></h3>
    <% end %>
    <%= yield %>
    <img class="glass" src="http://res.cloudinary.com/florismeininger/image/upload/v1508498216/ef06fd4633838842b5634cfbde4b43a4jpg_mvgwji.png">
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Whiskey Wall", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>